version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - app_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  centos6:
    container_name: app
    depends_on:
      - db
    build:
      context: ./centos6
      dockerfile: dockerfile
    volumes:
      - ./centos6/html:/var/www/html     
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
    app_db_data:
    